### PR TITLE
Reorganized index page & Workspace RCL demo

### PR DESCRIPTION
**Pull request by mannycolon**
# Describe what your pull request addresses

- [ ]

## Test Instructions

- [ ]

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-box3/next-js-template/29)

### CODE REVIEW

**Comment by mandolyte** [comment]
Found this:
0. delete all IndexedDB databases (or just the ones used by the template if known)
1. go to localhost:3000
2. login
3. The index page is shown
4. Click on the left "Example" card (localhost:3000/example)
5. after a few seconds, I am returned to the login page
6. Note that the URL is now localhost:3000/example
7. login again
8. This time you get the 404 page

Is this timing out on a page build and returning to the login?
@mannycolon

**Comment by mandolyte** [comment]
Once you get to the workspace demo, there is no way to return to the home page within the app itself.

Is there a standard way we want users to go back to the home page? -- or --
Should we make this a tabbed UI where there is a "Home" tab?

For consistency, I'd like to show how to implement how to return home... thoughts?
@mannycolon

**Comment by mannycolon** [comment]
> Found this: 0. delete all IndexedDB databases (or just the ones used by the template if known)
> 
> 1. go to localhost:3000
> 2. login
> 3. The index page is shown
> 4. Click on the left "Example" card (localhost:3000/example)
> 5. after a few seconds, I am returned to the login page
> 6. Note that the URL is now localhost:3000/example
> 7. login again
> 8. This time you get the 404 page
> 
> Is this timing out on a page build and returning to the login? @mannycolon

localhost:3000/example is not a page yet, therefore the 404 message. I added the example link /example for demonstrate how the UI looks like with four links in the index page but I'm hoping that it could be replaced by something else in the future

**Comment by mannycolon** [comment]
Either option feels good to me.

> Once you get to the workspace demo, there is no way to return to the home page within the app itself.
> 
> Is there a standard way we want users to go back to the home page? -- or -- Should we make this a tabbed UI where there is a "Home" tab?
> 
> For consistency, I'd like to show how to implement how to return home... thoughts? @mannycolon

Either option feels good to me.

**Comment by mandolyte** [comment]
What about in step 5 where it goes to the login page? I was expecting the
404 page.

Is it logging out because the page takes too long to build?

**Pull request merged**
